# Generated by Django 4.1.5 on 2023-01-09 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('phonenumber', models.CharField(max_length=50, verbose_name='Phone number')),
                ('address', models.CharField(max_length=1000, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterField(
            model_name='item',
            name='balance',
            field=models.PositiveIntegerField(verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('fishing', 'Fishing'), ('hunting', 'Hunting'), ('skiing', 'Skiing'), ('diving', 'Diving')], default='other', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='ItemsOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsorders', to='webapp.item', verbose_name='Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsorders', to='webapp.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Confirmed order',
                'verbose_name_plural': 'Confirmed orders',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='webapp.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
                'db_table': 'basket',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='items', to='webapp.order'),
        ),
    ]
